### ISSUE TITLE
Bravo!

### ISSUE THREAD

**Issue by ganch0** [CHEF-KOCH/NSABlocklist#1]
Hey CHEF-KOCH,

I've seen some posts of yours and am impressed by the knowledge of computer privacy and security that you posses.

Would you some day write a detailed guide on you configuration and how to best set up a computer (OS,browser and etc.) to be more secure from hacking, and government spying. There are lots of "guides" out there but for example they just recommend you installing a bunch of addonss on your firefox, where as from what I read by you, many of them are unneeded, and only slow down the performance.

I would love to, and am sure many more people as well, be able to learn how to best secure our computers from an expert like you.

Thank You very much!

**Comment by CHEF-KOCH** [comment]
Hello, and many thanks for your feedback! 

Hm, seems you speaking about an guide to pen-testing the OS/Software. I don't know if that is possible, I mean of course it is possible but this would need a lot of time and requires a lot of tools like whireshark/Burp to inspect the traffic, some developer tools to debug e.g. Firefox and of course a lot of time to write this guide and to explain each step and possible results. 

Well, about e.g. the addons situation. I also think that it doesn't even secure much things because to the simply reasons, if that addon is broken/compromised or not works for every page than we can say it's useless. So the first line of defense should (imho) to protect first the OS/Connection and after that we can/must secure the software like browser. 

Of course your words makes sense if you say e.g the performance factor which (sadly) will be a bit 'compromised' e.g. if we gonna to harden the DNS port (53) via DNSCrypt + Unbound (as a cache) it needs a bit more performance because the verification of the requests and on possible misconfiguration systems the udp will made a round-trip to the upstream resolver which coasts of course more bandwidth and time == performance. Well, this is only one example. 

Since I have not really ideas (well I have many but don't know where to start) what 'people' want these days, I think we maybe can use this topic (or open another one) to speak about 'wishes' which I simply could pick up and write about it. 

Because I might understand you what you want I can re-direct you to an 'old' (but still mostly working guide) which maybe fits for you, [just click this](http://crunchbang.org/forums/viewtopic.php?id=24722). Well, this guide or better this community is focused on Linux but most 'tips' are affecting every OS so they are still valid. Maybe I can pick up this guide, ask the orig. author to use it as a ground, update it and integrate my own stuff into it as a 'common' guide to harden the OS/Software. 

But I'm open-minded for every new and crazy idea.

**Comment by ganch0** [comment]
Hey, thank you for the quick response!

I didn't mean a guide to pen-testing the OS/Software, because like you say, this topic is much more vast than a simple guide, no matter how detailed it is.

What I meant is the guide with the link you pointed me to (thank you), however updated and integrated with your own stuff!

There are some guides out there, or pages which recommend privacy tools such as: <a href="https://www.epic.org/privacy/tools.html">this</a>, <a href="https://securityinabox.org/en">this</a>, <a href="https://prism-break.org/en/categories/windows/">and this</a>, but I feel like there are lots of myths and misinformation out there, and you do a really good job of showing them, and explaining about it.

For example, while everyone recommends HTTPS-Everywhere, you are the first person I know who said: "HTTPS-everywhere isn't necessary but much over-hyped with false statements or misleading information all over the web" and you went on explaining why, and the alternatives of it, which are better because it doesn't hurt the performance as much.
Same as Disconnect/Ghostery, which you said are better removed, and instead using uBlock, saving more memory.

I've also never came across "HOSTS file to block all known NSA / GCHQ / C.I.A. / F.B.I." like you have or your method of "block all the domains via hosts (works on every OS) and the custom filters which can't be blocked because it would break the entire domain. Benefit also is that you harden the entire OS not only Browser."
The Firefox hardening (users.js by pyllyukko) which you contribute to, or the regtweaks is also some great stuff.

So a common guide, similar to the one you showed me, however updated by you, explaining the whys and hows, which doesn't jeopardize performance and usability that much (I understand it will, however the goal is at the end of the day the computer to be still usable and with good performance - not to be slow and super annoying).

Since different people have different goals, the guide could have 2 versions. One for "normal" users - people who are computer literate and aware of hacking and government spying, and would like to eliminate that as much as they can, without getting overly technical about it, or sacrifice lots of their time, usability and day to day computer use. And a version for "advance" users - people who don't mind being over technical and going the extra mile, even if it means, noticeably slowing the performance and usability of the computer,  to truly trying to secure their computer as much as possible. The guide could be covering both Linux and Windows and overall to be a common guide to harden the OS/Software. 

So this is what I'm thinking. I believe it would be really helpful, and if you agree and have the time, I would love to see it come to light! Let me know what you think.

Thank you!!

**Comment by CHEF-KOCH** [comment]
Okay, thank your for your massive feedback, now I'm 'in' and understand what you really mean. 

I think I will use your idea about the two articles (thanks):

* Advanced Users Guide for experts with shell/cmd and other 'skills'
* .. normal users, which as you said doesn't want to spent that much time. 

In fact some external software will be however needed anyway due the fact it's more easier for people and of course update reasons. But I think I can give as much alternatives as possible.

Since I'm busy with the user.js addon I think I can't release much this year. So, sorry for the bad news but I will always respect user feedback, if someone have some topics I could look at like DNS or something like that I want to hear.

**Comment by ganch0** [comment]
Great, thank you very much! Looking forward to it!

**Comment by jinformatique** [comment]
Hi any news about a potential guide, I'm looking forward to it also!

**Comment by Atavic** [comment]
A complete Guide could be an entire book. Connecting various researches and repositories can be a good target.

**Comment by CHEF-KOCH** [comment]
There will be a book (currently 281 pages) which I sell for 10 euros (via donations), cause I not want to sell it over an external reseller and not everyone might have the money.

However the free version is [here](https://github.com/CHEF-KOCH/HWAB).

All of these tools are useless anyway, cause dnsapi.dll is not covered by any wpf firewall or hosts. That is why I decided to work now with ASN, cause some router firmware work great with that. IP blocking is not the future it's cancer to monitor and to maintain, holes are guaranteed.
