### ISSUE TITLE
VPN sections may need updating

### ISSUE THREAD

**Issue by Cauchon** [CHEF-KOCH/NSABlocklist#12]
I'd like to address two things around the VPN sections:

**1. [VPN providers which are not secure](https://github.com/CHEF-KOCH/NSABlocklist#vpn-providers-which-are-not-secure)**

Private Internet Access isn't on the list, but it's linked in the "Research" below. Private Internet Access' pre-shared key is 'mysafety'. 

https://www.privateinternetaccess.com/pages/client-support/osx-l2tp (see step 12 for shared key)

Therefore, shouldn't Private Internet Access be on the list of "VPN providers which are not secure"?

**2. [VPN Recommendation section](https://github.com/CHEF-KOCH/NSABlocklist#vpn-providers-which-are-not-secure)**
Should Private Internet Access be on this list? It has a pre-shared and is US based.

The concern around it being US based is around [National Security Letters (NSLs)](https://en.wikipedia.org/wiki/National_security_letter) which can be served without a judge's signature. Here are some links that prove that US VPNs may not be a great choice:
- [US says it doesn't need secret court's approval to ask for encryption backdoors](http://www.zdnet.com/article/us-says-it-does-not-need-courts-to-approve-encryption-backdoors/) 
- [The Lavabit case](https://en.wikipedia.org/wiki/Lavabit#Suspension_and_gag_order)
- [The case that privacytools.io makes](https://www.privacytools.io/#ukusa)

**Comment by CHEF-KOCH** [comment]
PIA can be trusted, I know about all the aguments that the servers and jurisdiction are in america and I'm aware of the fact that [L2TP uses pre-shared keys](https://www.ietf.org/rfc/rfc3193.txt). The thing is that hasn't much to do that the provider is now insecure or not trustable - it's a protocol standard. You can choose which protocol you want to use.

The second arguments is [about 14 eyes or 5 eyes countries](https://www.my-private-network.co.uk/vpn-provider-14-eyes-country-something-know/), and this article is basically BS. I will comment on some statements in this article (also fits most other articles based on that).

 > Online privacy experts such as privacytools.io recommend staying away from VPN providers based in the Fourteen Eyes, especially within the U.S. In essence, the U.S government could go to a VPN provider and demand access to customer data.

None of them are experts, there just bunch of people collecting tools which claim to 'harden' your security setup, no proof ever is given or it's not mentioned at the same time that such tools also could be already compromised. 

> Fortunately, My Private Network is located in Hong Kong; an ideal country for VPNs to be located in as there are no mandatory data retention laws. With no legal restrictions or government involvement, a Hong Kong based VPN company can really focus on their customer’s privacy. 

It oesn't matter if your server is located on the moon, USA or germany, every countrie has some interest getting your secrets (every yes!) and as long as the encryption is strong enough (you can setup it in PIA or OpenVPN config file) I see no reason to discuss about it since no one has cracked it, I checked today their official reddit channel. No proof, no hack, nothing. The server location DOES NOT MATTER, it's afact, what matters is encryption algorithm. 

That said all of these articles, rumours and 'conclusions' coming from pseudo-experts. Unless there is proof I not change anything here because it's pointless to change something based on 'guessing'. Don't believe the myth that there is a service which not logs or a service countrie that doesn't have any interest in getting data... 

- [Is Private Internet Access Located In A Fourteen Eyes Country?](https://helpdesk.privateinternetaccess.com/hc/en-us/articles/229705288-Is-Private-Internet-Access-Located-In-A-Fourteen-Eyes-Country-)
- [Five Eyes, Nine Eyes & 14-Eyes Countries and VPNs](https://thebestvpn.com/5-9-14-eyes-countries/)
- [Most VPN Services are Terrible](https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa)
