### ISSUE TITLE
Thank you. But some questions.

### ISSUE THREAD

**Issue by iphoneseven** [CHEF-KOCH/NSABlocklist#3]
Sorry for my bad English.
I am kind of new to this whole "privacy/security" thing so excuse my miss use of terms.
Thank you for this, I hope life is going good for you! :) 
But I have one question:
If the NSA is collecting things like facebook posts is hosts blocking effective? Does this block there malware? Or am I just misunderstanding this?

Sorry if I sound like a retard just want to know.

Thanks in advance :]

**Comment by CHEF-KOCH** [comment]
Oh, hey, and thanks I have forgotten to mention this in the Readme. 

Of course you're right that if you use social media/networks you're on your own. But in some cases an HOSTS or blacklist could help to e.g. lower the attack scenario by clicking on something which re-direct you to another 'infected/faked' page/login. 

The social engineering thing is very important, so some things can#t be fixed by installing an AntiVirus solution or other tools.

**Comment by iphoneseven** [comment]
Okay, I see, thank you :)

**Comment by JonnyRedHed** [comment]
How do you use the super ranges and hots file. i.e.  how to add it to windows 7 hosts file.   And / or  add to ublock origin add-on which take custom lists.

**Comment by CHEF-KOCH** [comment]
The ip's or list aren't designed to use it under Windows/Linux/Mac/Android itself, they are more for Routers. 

If there is a wish I could add a format which would fit in uMatrix/ublock or HOSTS, the thing is that it's horrible slow, especially if you not use Windows/Linux/Android/Mac OS own DNS resolver (like I do) this is because I say I not really designed it for such reasons.

**Comment by JonnyRedHed** [comment]
I see, thank you for explaining.   Is there a PM or email I can use to ask some other questions if your free to give some help.  I'm unsure on some things.  I saw your post on ghacks about that win7 privacy software Martin reviewed yesterday.

**Comment by CHEF-KOCH** [comment]
Yep, my contact details are visible, feel free to ask or make suggestions. Just click on my GitHub profile (nickname).
