### ISSUE TITLE
Google ranges?

### ISSUE THREAD

**Issue by DeadNumbers** [CHEF-KOCH/NSABlocklist#4]
Hi! Thanks you for this repo. But what about blocking google tracking?

**Comment by CHEF-KOCH** [comment]
```bash
8.8.4.0/24 (256 IP's)
8.8.8.0/24 (256 IP's)
8.34.208.0/21 (2.048 IP's)
8.34.216.0/21 ^^ 
8.35.192.0/21 ^^
8.35.200.0/21 ^^
23.236.48.0/20 (4.096 IP's)
23.251.128.0/19 (8.192 IP's)
64.233.160.0/19 (8.192 IP's)
64.233.160.0/24 (256 IP's)
```

The thing is none of them tracking, googletracking, ads services and such using own hosts/IP's. I consider to add it if I have more research.

There not even exist one entire list which blocks all of Google tracking services because it possible breaks pages + it's a legit method because some pages hardly need it, otherwise they will shutdown soon. We all need to pay our bills.

There is also a difference between 'spying', 'tracking' and collect data which really compromise your  security. I not know if I have enough research to be the one which can decide what you really can block.

**Comment by CHEF-KOCH** [comment]
I found 102.284 IP's which are _possible_ 'track' people. I need _several months_ to inspect them, don#t expect that I integrate them this year.

**Comment by DeadNumbers** [comment]
@CHEF-KOCH if you share this IP's, we help you inspect =)

**Comment by CHEF-KOCH** [comment]
I'm not sure if you understand, the IP's must be checked one by one. This can't be done with any tool, you only could inspect them to e.g. analyze the headers and check against which domain are behind but it's unclear if it really tracks you, there exist no program/script which 'check against' spying.

It usually takes a lot of time, since you must ensure that the domain not simply spawns another Ip to obfuscate the real purchase. Google analytics can do that, Google found a way to re-spawn on each request multiple ip's which makes it impossible to simply block google-analytics. You can test if you block it in your router and still see 'traffic' requests coming from it. Some certificate also can bypass it, which simply calls on blocked google-analytics ssl.analytics and I not even know how many domain names are registered behind it, because each time I check it, I will see another location and of course Ip's.

You only can reproduce this if you tunnel your entire incoming traffic and inspect it via Burp. If I would leak it, people may instantly report problems and I not want this. I take such stuff serious, I will never release unapproved stuff in public (for good reasons). 

There is also an [opt-out program by google](https://www.google.com/history/optout) which allows to configure several things, I never found something (after you disable everything) which tracks you, the stuff I only see are coming from external domains or internet web pages. As mentioned I not know if it's okay to block them without giving a warning that this also has negative effects on webpages, because we (again) need to pay our bills. 

The goverment pages are different, they can be blocked no matter what, because in times of twitter and co you get your information anyway even without them. But I not know when this will be end, the next ask for yahoo, another for xyz page. People should never forget that this layer of security not really matters, because a normal home pc is usually not a server system which has other attack scenarios. 

I think if someone really want secure things you can#t work with blacklist, whitelistening is what you may want. 

Long words, short answer I will not release it in public. I will investigate to see what makes sense to block.

**Comment by CHEF-KOCH** [comment]
Will be covered with the ASN update.
