### ISSUE TITLE
ipfilter.dat

### ISSUE THREAD

**Issue by ruy-benton** [CHEF-KOCH/NSABlocklist#6]
Thank you for your great list and effort.

This is't an issue .............. 

For many years I use and thousand out there:
ipfilter.dat to protect from many organizations - spy our traffic in Internet:
emule-security.org
www.bluetack.co.uk
www.cidr-report.org
upd.emule-security.org/fakeservers.txt
upd.emule-security.org/Inclusions.txt

And lots of other lists:
sourceforge.net/projects/peerguardian

Some of this sites disappear  (Hum ...    Why     :-) :-) :-)         )
I'm trying to create a clean file.

Please, the procedure or alternative lists.

Thank you for your brilliant work,
Ruy

**Comment by Atavic** [comment]
ipfilter.dat is a list developed by a few members of a sharing forum, last one seem to be:
Ip-Filter By Hooligan (15.02.2016), based on "eMule-Security IP-FILTER V1755" with 195.877 filters loaded from:

Bogon list - 14.02.16
Fake servers list - 14.02.16
Level 1 list - 09.08.15

Specific fakes and servers list for emule are still around. Note that a Kad-only emule is far more secure.

Firehol Level 1 is a big list that covers a lot: https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset

Same project lists other sources here: [https://github.com/firehol/blocklist-ipsets#which-ones-to-use](url)

The old Bluetack lists you mentioned are here: https://www.iblocklist.com/lists

**Comment by ruy-benton** [comment]
Thank you for your comments.

"Ip-Filter By Hooligan (15.02.2016)"
Please ... the date ... did you see?

Level 1 list - 09.08.15                    more than a year !!!!!!!!

I have all the lists in
sourceforge.net/projects/peerguardian
but the date ... !!!

We need every month new lists.

Thank,
Ruy

**Comment by Atavic** [comment]
Look at the lists in  the link provided, they are updated _every 1 day_.

I looked at _paranoid ipfilter_ in the past and you can recreate it with:
Level 1 (anti-p2p, RIAA...) + Level 2 (.com, MS...) + Level 3 + edu + bogon + badpeers + spider + hijacked + dshield

**Comment by ruy-benton** [comment]
https://www.iblocklist.com/lists ???
The bluetack.co.uk disappear from market ... and the lists ...  09.08.15
The "P2P Allow" ... we need to pay ...

Please explain ... where I can find free list?
In first post, I'm trie to compile a free list.

**Comment by Atavic** [comment]
Go to the site, scroll down to the lists authored by iblocklist.
Click on the ones you want. Right click on the _Update URL:_ then select all and copy.
Paste on your Browser's URL tab and then hit the 'go to' button.

**Comment by ruy-benton** [comment]
Most of this lists is for servers.

I have lots of servers in Internet and I make this lists from attacks SSH, Mail, port 80 - 443, etc.

I want the procedure for P2P ... and this can be an dynamic IP operated by 
Europol, Mossad, FBI, CIA, NSA, 

Level 1 (anti-p2p, RIAA...)       ... all are down

**Comment by Atavic** [comment]
Any p2p application acts as a server. The links on previous comment work fine to me.

**Comment by ruy-benton** [comment]
Hum ... But you don't have a Static IP ...

Ok I use 

http://www.qbittorrent.org

Please send my your ipfilter.dat to test

Thank you

**Comment by Atavic** [comment]
http://emule-security.org/ has a fresh one on top right.

**Comment by ruy-benton** [comment]
Helllllllllllllllllllllllllllllllllloooooooooooooooooooooooooooooo
What's going on??????????


In my first msg:
_______________________________________________________________
"For many years I use and thousand out there:
ipfilter.dat to protect from many organizations - spy our traffic in Internet:
emule-security.org"
_______________________________________________________________

In emule-security.org
 Level 1 list - 09.08.15               Can you read the date or not?



In the end you send me the same site with files from 2015?

**Comment by CHEF-KOCH** [comment]
www.bluetack.co.uk not updates their lists since years and it's known, dunno about the other pages but the tools and lists are mostly outdated. My list is up to date and there is no reason to update it 'daily' because a) if you are using an updated torrent client it already protects you with several other mechanism against a lot of attacks b) ipfilter not helps (there was on torrentfreaks an article about it c) quality lists need time to be approved 

With IP blocking you are [not secure anything](https://www.phildev.net/ipf/) because there exist bunch of other attack scenarios.  It lowers one aspect but it's not recommend for using in daily environment. If you are paranoid, then you need to work with whitelists and not with blacklists. 

I close this now because I don't see any reasons to talk about it, I update my lists as soon as I have time and I check them, I not add random stuff which I can't verify or trust from others.

**Comment by ruy-benton** [comment]
The site and the list is your ... but please **DON'T DELETE MY COMMENTS**.


> ... b) ipfilter not helps (there was on torrentfreaks an article about it ...

Lots of articles in that range posted by Film Industries :-) :-) :-)

And its all lies.


> ... With IP blocking you are not secure anything because there exist bunch of other attack scenarios. ...


And with your list the same thing (no 100% warranty)... but we use it
to block some sites.


and IPFILTER.DAT the same idea ... to protect some level.


Last Question:

If IPFILTER.DAT doesn't work
WHY 
qbittorrent.org
bitorrent
utorrent

use it???????
I don't' understand   :-) :-) :-)

I work in security ... servers - Firewall, Web, Mail
and block 200.000 IP address is better than ...... zero :-)  :-) :-)

You can send me email to further discuss this themes.

Regards,
Ruy

**Comment by Atavic** [comment]
Because you can create your own file, [here](https://gist.github.com/Atavic/e07d22209f8a603db38fa1c1b1da6911) is a single entry that will block a single IP Range.

**Comment by CHEF-KOCH** [comment]
Torrentfreak is not in any relationship sponsored by any film comp. IPfilter not helps and it's proven. 

> And with your list the same thing (no 100% warranty)... but we use it
to block some sites.

Yes, that's why it's mention within the readme. Ipfilter and this project are not even in any relationship, I not use the list for torrent, I use it for other reason and I wanted to share it, what you do with it is up to you. 


I delete you post because it was already the same (full qupte) from your first topic. 

I not see what is the benefit exept wasting my time to talk about this, I update everything if I have proof I'm not any xyz page which picks up random stuf to show 'look new update'. I not want to work like this. 

if you want security you can use hitelist and not blacklist what I recommed. Because blacklist is not secure. DNS could be manipulated and other attacks to bypass hosts/ip blocking. 

Last time I answer on this. If you think everything is a lie then show proof or leave this project because I not want to waste my time on 'what if questions' or FUD.
