### ISSUE TITLE
Italian internet providers blocked

### ISSUE THREAD

**Issue by bryce-lynch** [CHEF-KOCH/NSABlocklist#81]
Just FYI, your hosts file would block most italian users as it includes the **official** dns servers of the major internet providers in Italy (*.fastweb.it, *.libero.it, *.interbusiness.it *.iunet.it, *.tiscalinet.it, *.tiscali.it, *.starlink.it), universities (*.unina.it, *.univaq.it, *.unirc.it), and even the mail server of the italian Institute of Chemical and Technology of Polymers (mail.irtemp.na.cnr.it).

I don't know what your sources are, but many public blocklists I've seen around include perfectly legit european hosts (that's why I make my own lists using custom RIPE db mining scripts).

**Comment by CHEF-KOCH** [comment]
* Most EU CDN's as well as ISP working directly together with authorities. This is shown multiple times in the NSA leaks, in specific Wiki leaks (all documents are in this repository). These sources have credibility.
* I DO NOT make exceptions, if you're affected you should consider switching the ISP/CDN and not the other way around because there is no point to block specific connections but ultimately allow your ISP as well as authorities to monitor your connection. The list of affected ISP's is also listed (CDN's are on the to-do until I have enough evidence to lst them).

**Comment by bryce-lynch** [comment]
> if you're affected you should consider switching the ISP/CDN and not the other way around

Since you've blocked every single major italian internet provider (and all others would still need to use National Service Providers like interbusiness, which you're trying to avoid), there's no point in switching. Anyway I don't trust every thing I see on Cryptome since anyone can anonymously post made-up stories, but that's just me. I just wanted to let you know. Cheers.

**Comment by CHEF-KOCH** [comment]
It's incorrect that you say "every single major Italian internet provider". The list blocks several known and compromised DNS servers, if your ISP uses them then you should ask them why.

> Anyway I don't trust every thing I see on Cryptome since anyone can anonymously post made-up stories

Please provide evidence for your claim, the stuff which you can submit will be reviewed and checked. It's like saying "Snowden makes things up" because you cannot prove him wrong because there is nothing to compare against. The documents are been checked trough several instances. 

Cryptome exist longer than Google and has more credibility than most "leaker pages". I basically vouch for the site and people behind it and I do not let this page been destroyed by wrong accusations.
